// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCId6tiNvSDJQQNg--aQlduijum7yYGPjQ',
    appId: '1:190708644000:web:1759181d4ed5299397f1c5',
    messagingSenderId: '190708644000',
    projectId: 'indoor-tracking-bd538',
    authDomain: 'indoor-tracking-bd538.firebaseapp.com',
    databaseURL: 'https://indoor-tracking-bd538-default-rtdb.firebaseio.com',
    storageBucket: 'indoor-tracking-bd538.appspot.com',
    measurementId: 'G-PJSL977S3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgAlR2NFya3J8bx1wk7yQjeS1iPPlRCmA',
    appId: '1:190708644000:android:5bff11c8da797cb997f1c5',
    messagingSenderId: '190708644000',
    projectId: 'indoor-tracking-bd538',
    databaseURL: 'https://indoor-tracking-bd538-default-rtdb.firebaseio.com',
    storageBucket: 'indoor-tracking-bd538.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfxB7xjB8NtK7smNWRjhteQM_HUl6AC3Q',
    appId: '1:190708644000:ios:ca02a68dbf128f4b97f1c5',
    messagingSenderId: '190708644000',
    projectId: 'indoor-tracking-bd538',
    databaseURL: 'https://indoor-tracking-bd538-default-rtdb.firebaseio.com',
    storageBucket: 'indoor-tracking-bd538.appspot.com',
    iosClientId: '190708644000-tbf40if3cd5prpdva5i6ua8cqrrgj2i2.apps.googleusercontent.com',
    iosBundleId: 'com.aries.indoortracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfxB7xjB8NtK7smNWRjhteQM_HUl6AC3Q',
    appId: '1:190708644000:ios:93f3b4c5b7c6468297f1c5',
    messagingSenderId: '190708644000',
    projectId: 'indoor-tracking-bd538',
    databaseURL: 'https://indoor-tracking-bd538-default-rtdb.firebaseio.com',
    storageBucket: 'indoor-tracking-bd538.appspot.com',
    iosClientId: '190708644000-kq0fm3netpq7l3usdcm2nrviu7h6lg3l.apps.googleusercontent.com',
    iosBundleId: 'com.aries.indoortracking.RunnerTests',
  );
}
